// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0NmIJtopcs3LnoOCA4WtFND4xiaEVQuI',
    appId: '1:362576348509:android:1b1f8ac38a81229ae394b4',
    messagingSenderId: '362576348509',
    projectId: 'my-cool-chat',
    storageBucket: 'my-cool-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcoJi_AscG2S7Jb-zDQOeZTcv4ZUFK40',
    appId: '1:362576348509:ios:999baff58feb8a80e394b4',
    messagingSenderId: '362576348509',
    projectId: 'my-cool-chat',
    storageBucket: 'my-cool-chat.appspot.com',
    iosClientId: '362576348509-b99ansom7bikagm51hnemrdqoiljkthi.apps.googleusercontent.com',
    iosBundleId: 'com.sinasamii.ioschat',
  );
}
